name: Playwright Tests (Docker)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t pw-tests .

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          docker run --rm \
            -e BASE_URL=${{ secrets.BASE_URL }} \
            -v $(pwd)/playwright-report:/app/playwright-report \
            pw-tests npx playwright test --reporter=html

      - name: Upload Playwright HTML report
        if: always() # supaya report tetap upload walau test fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report
